serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = {{ .Envs.FRP_SERVER_PORT }}
auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

[[proxies]]
name = "yorozuya-web"
type = "tcp"
localIP = "frontend"
localPort = 80
remotePort = {{ .Envs.FRP_REMOTE_PORT }}
